name: Checkout Workflow
on: push


jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name : Step1
        uses: actions/checkout@v4

      - name: Step2
        run: ls

      - name: Step3
        run: pwd

      - name: Step4
        run: cat Readme.md

      - name: Step5
        run: test -f Readme11.md

      - name: Step6
        if: ${{ success() }}
        run: echo "Readme.md file exists"

      - name: Step7
        run: echo "Workflow finished"
