name: Checkout Workflow
on: push


jobs:
  checkout-job:
    runs-on: ubuntu-latest

    steps:
      - name : Step1
        uses: actions/checkout@v4

      - name: Step2
        run: ls

      - name: Step3
        run: pwd

      - name: Step4
        run: cat Readme.md

      - name: Step5
        run: test -f RReadme.md && echo "Readme.md exists" || echo "Readme.md does not exist"